[package]
name = "gpui_effects"
version = "0.1.0"
publish.workspace = true
edition.workspace = true
license = "MIT"
readme = "README.md"

[dependencies]
anyhow.workspace = true
smallvec.workspace = true
accesskit.workspace = true
gpui.workspace = true
image.workspace = true
refineable.workspace = true
scheduler.workspace = true
uic_macros.workspace = true

[lints]
workspace = true

[dev-dependencies]
gpui = { workspace = true, features = ["test-support", "automation"] }
gpui_platform = { workspace = true, features = ["font-kit", "wayland", "x11"] }
naga.workspace = true
pollster.workspace = true
wgpu.workspace = true
