-keep class dev.gpui.android.GpuiSession { *; }
-keep class dev.gpui.android.TextInputState { *; }
-keep class dev.gpui.android.SelectedDocument { *; }
-keep class dev.gpui.android.DocumentOutput { *; }
-keep class dev.gpui.android.FileStore { *; }
-keep class dev.gpui.android.CredentialStore { *; }
-keep class dev.gpui.android.StoredCredential { *; }
-keep class dev.gpui.android.MediaSession { *; }
