[package]
name = "uic"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
serde = { workspace = true, features = ["derive"] }
strum = { workspace = true, features = ["derive", "strum_macros"] }
unicode-segmentation = { workspace = true }
anyhow = { workspace = true }
scheduler = { workspace = true }
chrono = { workspace = true }
gpui = { workspace = true }
gpui_effects = { workspace = true }
rust-embed = { version = "8.11", features = ["include-exclude"] }
uic_macros = { workspace = true }


[dev-dependencies]
gpui = { workspace = true, features = ["test-support"] }
gpui_wgpu = { workspace = true }
gpui_platform = { workspace = true, features = ["wayland", "font-kit"] }
